name: Publish content to pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Download Sphinx Binaries
      run: |
          ./gradlew downloadBinaries
          chmod +x ./bin/sphinx.linux-x86_64
    - name: Build with Gradle
      run: ./gradlew clean site
    - name: Show content
      run: ls -a ./build/sphinx-site
    - name: Archive artifact
      shell: sh
      if: runner.os == 'Linux'
      run: |
        chmod -c -R +rX ./build/sphinx-site | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
        tar \
          --dereference --hard-dereference \
          --directory ./build/sphinx-site \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --exclude=.git \
          --exclude=.github \
          .
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'github-pages'
        path: ${{ runner.temp }}/artifact.tar
        retention-days: "1"
        if-no-files-found: error  
