name: Publish content to pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Download Sphinx Binaries
      run: |
          ./gradlew downloadBinaries
          chmod +x ./bin/sphinx.linux-x86_64
    - name: Build with Gradle
      run: ./gradlew clean site
    - name: Show content
      run: ls -a ./build
